import { Template } from '@/types/template';

/** Single template definition: unique title, description, and content. No #1/#2 duplicates. */
interface TemplateDef {
  title: string;
  description: string;
  tag: string;
  /** Optional: multiple tags for filter (e.g. Wedding + Productivity + Personal). Defaults to [def.tag]. */
  tags?: string[];
  whats_inside: string[];
  is_free: boolean;
  price_cents?: number;
  is_subscription_included?: boolean;
  allow_one_time_purchase?: boolean;
  featured?: boolean;
  /** Optional override so template appears first on gallery page 1 when featured-first sort is used */
  popularity_score?: number;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim();
}

/** Deterministic but varied rating/count/popularity from title (no random per load). */
function seedFromTitle(title: string): number {
  let h = 0;
  for (let i = 0; i < title.length; i++) h = (h << 5) - h + title.charCodeAt(i);
  return Math.abs(h);
}

function buildTemplate(def: TemplateDef, index: number): Template {
  const baseSlug = slugify(def.title);
  const slug = `${baseSlug}-${index}`;
  const seed = seedFromTitle(def.title + index);
  const now = new Date().toISOString();

  const rating = 4.5 + (seed % 50) / 100;
  const ratingCount = 12 + (seed % 420);
  const popularityScore = def.popularity_score ?? (seed % 100);

  const isFree = def.is_free;
  const price = isFree ? null : (def.price_cents ?? 1999);
  const subIncluded = def.is_subscription_included ?? (!isFree && (seed % 3 !== 0));
  const oneTime = def.allow_one_time_purchase ?? (!isFree && (seed % 2 === 0));

  return {
    id: `static-${slug}`,
    slug,
    title: def.title,
    description: def.description,
    tags: def.tags ?? [def.tag],
    price_cents: price,
    is_free: isFree,
    is_subscription_included: subIncluded,
    allow_one_time_purchase: oneTime,
    thumbnail_url: null,
    gallery_urls: [],
    featured: def.featured ?? false,
    popularity_score: popularityScore,
    whats_inside: def.whats_inside,
    created_at: now,
    updated_at: now,
    rating: Math.round(rating * 100) / 100,
    rating_count: ratingCount,
  };
}

const TEMPLATE_DEFINITIONS: TemplateDef[] = [
  // —— First-page featured (Reading List, Student and Lesson Planner) ——
  {
    title: 'Reading List',
    description: 'Track every book you read or want to read in one place. Log title, author, reading progress, your rating, and personal notes or takeaways. Filter by status (want to read / reading / read), sort by date or rating, and build a visual list that grows with you.',
    tag: 'Knowledge',
    whats_inside: [
      'Book database with title and author',
      'Reading progress (%, page count, or status)',
      'Star rating and short review',
      'Reading notes and highlights',
      'Want to read / Reading / Read status',
      'Filter and sort by date or rating',
    ],
    is_free: true,
    featured: true,
    popularity_score: 99,
  },
  {
    title: 'Student and Lesson Planner',
    description: 'A practical student and lesson planner that looks like notes on a bulletin board—perfect for organizing classes, assignments, and study plans. Plan lessons and units, track homework and due dates, and keep everything in one visual place. Great for students and tutors who want clarity without the clutter.',
    tag: 'Student',
    whats_inside: [
      'Lesson and unit planning pages',
      'Assignment tracker with due dates',
      'Class schedule overview',
      'Study plan and checklist',
      'Bulletin-board style layout',
      'Quick links to subjects and resources',
    ],
    is_free: true,
    featured: false,
    popularity_score: 99,
  },
  // —— Productivity (Notion-style: planners, second brain, GTD) ——
  {
    title: '12 Week Year Planner',
    description: 'The 12 Week Year is a powerful time management system that can help you achieve your goals and objectives in a fraction of the time it would normally take. This template is designed to help you plan and execute your 12 Week Year Goals and track your progress along the way.',
    tag: 'Productivity',
    whats_inside: [
      '12-week goal tracker with progress %',
      'Weekly tactic planner (Mon–Fri time blocks)',
      'Weekly scorecard with auto execution score',
      'Friday review & reflection template',
      'Vision & long-term goal alignment page',
      'Cycle rollover checklist for next 12 weeks',
    ],
    is_free: true,
    featured: true,
    popularity_score: 92,
  },
  {
    title: 'Second Brain & PKM',
    description: 'Capture ideas, link notes, and build a personal knowledge base. PARA or CODE-friendly structure with inbox, projects, and archives.',
    tag: 'Productivity',
    whats_inside: ['Inbox & quick capture', 'Linked databases by area', 'MOC (Maps of Content)', 'Review rituals'],
    is_free: true,
  },
  {
    title: 'Weekly Execution Dashboard',
    description: 'One dashboard for the week: top priorities, daily blocks, and a simple review so you end each week with clarity.',
    tag: 'Productivity',
    whats_inside: ['Weekly priorities', 'Day-by-day layout', 'Time blocking placeholders', 'Week in review template'],
    is_free: true,
  },
  {
    title: 'Deep Work Scheduler',
    description: 'Block focus time, limit distractions, and track deep work sessions. Inspired by Cal Newport’s deep work principles.',
    tag: 'Productivity',
    whats_inside: ['Focus blocks calendar', 'Session log', 'Rules & rituals', 'Weekly depth summary'],
    is_free: true,
  },
  {
    title: 'GTD-Inspired Task System',
    description: 'Capture, clarify, organize, reflect, and engage. A full GTD-style setup with inbox, next actions, and project lists.',
    tag: 'Productivity',
    whats_inside: ['Inbox', 'Next actions by context', 'Projects with outcomes', 'Weekly review checklist'],
    is_free: false,
    price_cents: 1499,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Eisenhower Matrix & Priorities',
    description: 'Sort tasks by urgent/important. Views for do first, schedule, delegate, and eliminate so you focus on what matters.',
    tag: 'Productivity',
    whats_inside: ['Matrix database', 'Views by quadrant', 'Priority tags', 'Daily top 3'],
    is_free: true,
    popularity_score: 87,
  },
  {
    title: 'Meeting Notes & Agendas',
    description: 'Templates for meeting agendas, notes, and action items. Keep meetings short and outcomes clear.',
    tag: 'Productivity',
    whats_inside: ['Agenda template', 'Notes with action items', 'Meeting log database', 'Follow-up tracker'],
    is_free: true,
  },
  {
    title: 'Personal Dashboard & Life OS',
    description: 'One home for tasks, goals, habits, and notes. A calm overview of what’s going on in work and life.',
    tag: 'Productivity',
    whats_inside: ['Dashboard overview', 'Key metrics', 'Quick links', 'Today & this week'],
    is_free: false,
    price_cents: 1999,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Energy & Time Audit',
    description: 'Log how you spend time and energy. Spot patterns and adjust so high-leverage work gets your best hours.',
    tag: 'Productivity',
    whats_inside: ['Time log database', 'Energy levels', 'Category tags', 'Weekly summary views'],
    is_free: true,
  },
  {
    title: 'Quarterly OKR & Review',
    description: 'Set objectives and key results per quarter. Track progress and run a simple retrospective so the next quarter is better.',
    tag: 'Productivity',
    whats_inside: ['OKR database', 'Progress tracking', 'Quarterly review template', 'Wins & learnings'],
    is_free: false,
    price_cents: 1299,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Someday / Maybe List',
    description: 'Park ideas and dreams without cluttering your task list. Review periodically and promote items when the time is right.',
    tag: 'Productivity',
    whats_inside: ['Someday database', 'Categories', 'Review schedule', 'Promote to project flow'],
    is_free: true,
  },
  {
    title: 'Morning & Evening Routines',
    description: 'Templates for morning planning and evening review. Start and end the day with intention.',
    tag: 'Productivity',
    whats_inside: ['Morning template', 'Evening review', 'Routine checklist', 'Streak tracker'],
    is_free: true,
  },
  {
    title: 'Project Kickoff & Brief',
    description: 'One template for starting any project: goal, scope, stakeholders, and first steps so nothing is missed.',
    tag: 'Productivity',
    whats_inside: ['Project brief', 'Scope & success criteria', 'Stakeholders', 'Kickoff checklist'],
    is_free: true,
  },
  {
    title: 'Read It Later & Reading List',
    description: 'Save articles and books to read. Track status and notes so your reading list stays manageable.',
    tag: 'Productivity',
    whats_inside: ['Reading list database', 'Status & priority', 'Notes & highlights', 'Categories'],
    is_free: true,
  },
  {
    title: 'Decision Log',
    description: 'Record important decisions, context, and outcomes. Turn past decisions into a searchable log for your future self.',
    tag: 'Productivity',
    whats_inside: ['Decision database', 'Context & options', 'Outcome tracking', 'Tags by area'],
    is_free: true,
  },
  {
    title: 'Focus Mode Checklist',
    description: 'Pre-focus checklist (close tabs, silence phone) and post-focus log. Build a repeatable deep work ritual.',
    tag: 'Productivity',
    whats_inside: ['Pre-focus checklist', 'Session log', 'Interruption log', 'Weekly focus stats'],
    is_free: true,
  },
  {
    title: 'Weekly Review System',
    description: 'A guided weekly review: clear inbox, update lists, review goals, and plan the next week in one place.',
    tag: 'Productivity',
    whats_inside: ['Review checklist', 'Inbox zero', 'Goals check-in', 'Next week preview'],
    is_free: false,
    price_cents: 999,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Backlog & Ideas Hub',
    description: 'One backlog for product, content, or life ideas. Prioritize, tag, and move items into active work when ready.',
    tag: 'Productivity',
    whats_inside: ['Backlog database', 'Priority & effort', 'Status workflow', 'Sprint or batch views'],
    is_free: true,
  },
  {
    title: 'Personal CRM & Relationships',
    description: 'Keep track of people you care about: last contact, notes, and follow-up reminders so relationships don’t slip.',
    tag: 'Productivity',
    whats_inside: ['Contacts database', 'Last contact date', 'Notes & context', 'Follow-up reminders'],
    is_free: true,
  },
  {
    title: 'Life Operating System',
    description: 'An all-in-one life OS: areas of life, goals, projects, and reviews. Inspired by life design and building a second brain.',
    tag: 'Productivity',
    whats_inside: ['Life areas', 'Goals by area', 'Projects & tasks', 'Monthly review'],
    is_free: false,
    price_cents: 2499,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },

  // —— Student ——
  {
    title: 'All-in-One Student OS',
    description: 'Courses, assignments, exams, and study sessions in one place. Built for semester planning and last-minute prep.',
    tag: 'Student',
    whats_inside: ['Course database', 'Assignments & due dates', 'Exam calendar', 'Study session log'],
    is_free: true,
    popularity_score: 94,
  },
  {
    title: 'Semester Planner & GPA Tracker',
    description: 'Plan your semester, track grades, and project GPA. Stay on top of credits and requirements.',
    tag: 'Student',
    whats_inside: ['Semester overview', 'Grade tracker', 'GPA calculator', 'Credit checklist'],
    is_free: true,
    popularity_score: 91,
  },
  {
    title: 'Monthly Planner',
    description: 'This monthly planner is intentionally simple. You can enhance it with deadlines, reflections, or metrics as your planning needs grow.',
    tag: 'Student',
    whats_inside: ['Monthly view', 'Deadlines & key dates', 'Reflection space', 'Optional metrics'],
    is_free: true,
    popularity_score: 88,
  },
  {
    title: 'My Class Schedule',
    description: 'Meet My Class Schedule your minimalist planner to keep your days balanced and stress-free.',
    tag: 'Student',
    whats_inside: ['Weekly calendar', 'Daily to-do list', 'Class blocks', 'Balance view'],
    is_free: true,
    popularity_score: 84,
  },
  {
    title: 'Lecture Notes & Revision',
    description: 'Structured templates for lecture notes and revision. Link to courses and exams for easy review.',
    tag: 'Student',
    whats_inside: ['Note templates', 'Course links', 'Revision checklist', 'Flashcard prompts'],
    is_free: true,
  },
  {
    title: 'Assignment Tracker & Deadlines',
    description: 'List every assignment with due dates and status. Never miss a deadline again.',
    tag: 'Student',
    whats_inside: ['Assignment database', 'Due date calendar', 'Status & priority', 'Submit checklist'],
    is_free: true,
  },
  {
    title: 'Study Group & Collaboration',
    description: 'Coordinate study groups: sessions, topics, and shared notes so everyone stays aligned.',
    tag: 'Student',
    whats_inside: ['Study session log', 'Topic tracker', 'Shared notes', 'Member list'],
    is_free: true,
  },
  {
    title: 'Research & Thesis Planner',
    description: 'Plan research, literature, and thesis chapters. Track sources and progress in one workspace.',
    tag: 'Student',
    whats_inside: ['Research questions', 'Literature database', 'Chapter outline', 'Source tracker'],
    is_free: false,
    price_cents: 1999,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Exam Countdown & Revision Plan',
    description: 'Countdown to exam day with a structured revision plan. Allocate time by topic and track what’s done.',
    tag: 'Student',
    whats_inside: ['Exam dates', 'Revision calendar', 'Topic checklist', 'Practice tests log'],
    is_free: true,
  },
  {
    title: 'Student Budget & Expenses',
    description: 'Track student income, expenses, and subscriptions. Simple categories so you know where your money goes.',
    tag: 'Student',
    whats_inside: ['Income & expenses', 'Categories', 'Monthly summary', 'Subscription list'],
    is_free: true,
  },
  {
    title: 'Course Syllabus Tracker',
    description: 'Break down each syllabus into modules and tasks. Turn “read chapter 3” into checkable items.',
    tag: 'Student',
    whats_inside: ['Syllabus database', 'Modules & readings', 'Task breakdown', 'Progress view'],
    is_free: true,
  },
  {
    title: 'Study Habit Tracker',
    description: 'Log study hours and subjects daily. Spot patterns and keep yourself accountable.',
    tag: 'Student',
    whats_inside: ['Daily log', 'Subject tags', 'Weekly totals', 'Streak & goals'],
    is_free: true,
  },
  {
    title: 'Lab Notes & Experiments',
    description: 'Structured lab notes: hypothesis, method, results, and conclusions. Perfect for science and design courses.',
    tag: 'Student',
    whats_inside: ['Experiment template', 'Results & data', 'Conclusion', 'Lab database'],
    is_free: true,
  },
  {
    title: 'Scholarship & Application Tracker',
    description: 'Track scholarships and applications: deadlines, requirements, and status so nothing falls through the cracks.',
    tag: 'Student',
    whats_inside: ['Application database', 'Deadlines', 'Requirements checklist', 'Status workflow'],
    is_free: true,
  },
  {
    title: 'Group Project Hub',
    description: 'One space for group projects: tasks, owners, meetings, and files so the whole team stays in sync.',
    tag: 'Student',
    whats_inside: ['Task list with owners', 'Meeting notes', 'File links', 'Deadline view'],
    is_free: true,
  },
  {
    title: 'Reading List by Course',
    description: 'Track required and optional readings per course. Mark as read and add notes.',
    tag: 'Student',
    whats_inside: ['Reading database', 'Course link', 'Status & notes', 'Due dates'],
    is_free: true,
  },
  {
    title: 'Office Hours & Tutor Tracker',
    description: 'Plan which office hours or tutoring sessions to attend. Log questions and takeaways.',
    tag: 'Student',
    whats_inside: ['Schedule view', 'Question log', 'Takeaways', 'Instructor contact'],
    is_free: true,
  },
  {
    title: 'Student Wellness & Balance',
    description: 'Track sleep, exercise, and stress alongside academics. Simple check-ins to stay balanced.',
    tag: 'Student',
    whats_inside: ['Daily check-in', 'Sleep & exercise', 'Mood optional', 'Weekly reflection'],
    is_free: true,
  },
  {
    title: 'Capstone & Project Showcase',
    description: 'Plan and document your capstone or final project. From proposal to presentation and portfolio.',
    tag: 'Student',
    whats_inside: ['Proposal template', 'Milestones', 'Documentation', 'Portfolio page'],
    is_free: false,
    price_cents: 1499,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Study Abroad Planner',
    description: 'Plan courses, housing, and travel for study abroad. Keep visas, contacts, and itineraries in one place.',
    tag: 'Student',
    whats_inside: ['Course planning', 'Housing & travel', 'Visa checklist', 'Contacts'],
    is_free: true,
  },
  {
    title: 'Note-Taking Methods Library',
    description: 'Templates for Cornell, outline, and other note-taking methods. Pick the right structure for each class.',
    tag: 'Student',
    whats_inside: ['Cornell template', 'Outline template', 'Concept map', 'Method guide'],
    is_free: true,
  },
  {
    title: 'Academic Year at a Glance',
    description: 'One-page view of the whole academic year: terms, exams, and key dates so you can plan ahead.',
    tag: 'Student',
    whats_inside: ['Year calendar', 'Term blocks', 'Exam dates', 'Holidays & breaks'],
    is_free: true,
  },

  // —— Personal Finance (Notion-style: expense tracker, budget, vision) ——
  {
    title: 'Expense Tracker 2026',
    description: 'Log daily expenses with categories and optional notes. Simple views to see where your money goes each month.',
    tag: 'Personal Finance',
    whats_inside: ['Expense database', 'Categories', 'Monthly views', 'Summary by category'],
    is_free: true,
  },
  {
    title: 'Monthly Budget',
    description: 'Plan income and expenses by category. Track actual vs budget and adjust as you go.',
    tag: 'Personal Finance',
    whats_inside: ['Budget by category', 'Income tracker', 'Actual vs budget', 'Monthly review'],
    is_free: true,
  },
  {
    title: '2026 Vision Board & Year Compass',
    description: 'Reflect on the past year and set intentions for the next. Vision board, word of the year, and goals in one space.',
    tag: 'Personal Finance',
    whats_inside: ['Year compass prompts', 'Vision board area', 'Word of the year', 'Goals & intentions'],
    is_free: true,
  },
  {
    title: 'Net Worth Tracker',
    description: 'Track assets and liabilities over time. One dashboard for your net worth and progress to goals.',
    tag: 'Personal Finance',
    whats_inside: ['Assets database', 'Liabilities', 'Net worth over time', 'Goal tracking'],
    is_free: false,
    price_cents: 1999,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Subscription & Recurring Costs',
    description: 'List every subscription and recurring bill. See total monthly spend and cancel what you don’t use.',
    tag: 'Personal Finance',
    whats_inside: ['Subscription list', 'Monthly cost', 'Renewal dates', 'Usage notes'],
    is_free: true,
  },
  {
    title: 'Savings Goals & Buckets',
    description: 'Set savings goals and track progress. Emergency fund, vacation, or big purchase — all in one place.',
    tag: 'Personal Finance',
    whats_inside: ['Goals database', 'Target & current', 'Timeline', 'Progress bar view'],
    is_free: true,
  },
  {
    title: 'Bill Calendar & Due Dates',
    description: 'All bills and due dates in one calendar. Never miss a payment again.',
    tag: 'Personal Finance',
    whats_inside: ['Bills database', 'Due dates', 'Amount & payee', 'Paid checkbox'],
    is_free: true,
  },
  {
    title: 'Investment & Portfolio Log',
    description: 'Log investments and track performance. Simple place to record buys, sells, and notes (not advice).',
    tag: 'Personal Finance',
    whats_inside: ['Holdings list', 'Purchase log', 'Dividends', 'Notes & links'],
    is_free: false,
    price_cents: 2499,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Tax Prep & Document Checklist',
    description: 'Checklist of documents and info you need for taxes. Track what you’ve gathered and what’s pending.',
    tag: 'Personal Finance',
    whats_inside: ['Document checklist', 'Income sources', 'Deductions', 'Deadline tracker'],
    is_free: true,
  },
  {
    title: 'Family Budget & Shared Expenses',
    description: 'Shared budget for households: income, fixed costs, and discretionary spending so everyone stays aligned.',
    tag: 'Personal Finance',
    whats_inside: ['Shared budget', 'Categories', 'Who pays what', 'Monthly review'],
    is_free: false,
    price_cents: 1799,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Debt Payoff Tracker',
    description: 'List debts, rates, and minimums. Track payoff progress with avalanche or snowball approach.',
    tag: 'Personal Finance',
    whats_inside: ['Debt list', 'Balance & rate', 'Payoff plan', 'Progress view'],
    is_free: true,
  },
  {
    title: 'Side Income & Freelance Log',
    description: 'Log side gig and freelance income by client or project. Simple P&L view for your side hustle.',
    tag: 'Personal Finance',
    whats_inside: ['Income log', 'Client/project', 'Expenses', 'Monthly total'],
    is_free: true,
  },
  {
    title: 'Financial Goals & Milestones',
    description: 'Set financial milestones (emergency fund, down payment, etc.) and track progress with dates and notes.',
    tag: 'Personal Finance',
    whats_inside: ['Goals database', 'Target amount', 'Current progress', 'Timeline'],
    is_free: true,
  },
  {
    title: 'Gift & Donation Tracker',
    description: 'Track gifts given and donations for the year. Useful for budgeting and tax deduction records.',
    tag: 'Personal Finance',
    whats_inside: ['Gift/donation log', 'Recipient', 'Amount', 'Date'],
    is_free: true,
  },
  {
    title: 'Cash Flow Overview',
    description: 'Monthly cash in vs cash out. See patterns and plan for low-cash months.',
    tag: 'Personal Finance',
    whats_inside: ['Income by month', 'Expenses by month', 'Net flow', 'Notes'],
    is_free: true,
  },
  {
    title: 'Holiday & Gift Budget',
    description: 'Budget for holidays and gifts: list people, budget per person, and track what you’ve spent.',
    tag: 'Personal Finance',
    whats_inside: ['Gift list', 'Budget per person', 'Spent', 'Ideas & links'],
    is_free: true,
  },
  {
    title: 'Financial Review Template',
    description: 'Quarterly or yearly financial review: what went well, what to change, and next period goals.',
    tag: 'Personal Finance',
    whats_inside: ['Review prompts', 'Wins & challenges', 'Goals', 'Action items'],
    is_free: true,
  },
  {
    title: 'Price Comparison & Big Purchases',
    description: 'Compare options for big purchases. Track specs, prices, and pros/cons before you buy.',
    tag: 'Personal Finance',
    whats_inside: ['Purchase database', 'Options comparison', 'Links', 'Decision log'],
    is_free: true,
  },
  {
    title: 'Money Mindset & Habits',
    description: 'Reflect on money habits and mindset. Prompts and check-ins to align spending with values.',
    tag: 'Personal Finance',
    whats_inside: ['Reflection prompts', 'Habit tracker', 'Values alignment', 'Monthly check-in'],
    is_free: true,
  },

  // —— Travel ——
  {
    title: 'Travel Bucket List & Wish List',
    description: `This Travel Wishlist / Bucket List template helps you organize every destination you want to visit—whether it's a country, city, or specific place. Add inspiring photos to bring your travel dreams to life and keep everything visually appealing and motivating.

For each destination, you can store useful details such as travel type, ideal travel time, duration, travel buddy, and planned dates. A simple status system lets you track whether a trip is want to go, in planning, or visited.

Perfect for travelers who want clarity and inspiration in one place, this template turns scattered ideas into an organized travel roadmap.`,
    tag: 'Travel',
    whats_inside: [
      'Destination gallery with cover photos',
      'Status workflow: Dreaming → Planning → Explored',
      'Filter by continent, season & priority',
      'Budget estimate per destination',
      'Packing checklist linked to each trip',
      'Booking links & travel notes per entry',
    ],
    is_free: true,
    featured: true,
    popularity_score: 90,
  },
  {
    title: 'Trip Planner & Itinerary',
    description: 'Plan a single trip: flights, lodging, daily itinerary, and packing list in one place.',
    tag: 'Travel',
    whats_inside: ['Trip overview', 'Day-by-day itinerary', 'Bookings', 'Packing list'],
    is_free: true,
  },
  {
    title: 'Packing List by Trip Type',
    description: 'Reusable packing lists for beach, city, work, or camping. Check off as you pack.',
    tag: 'Travel',
    whats_inside: ['Templates by type', 'Checklist', 'Optional items', 'Tips'],
    is_free: true,
  },
  {
    title: 'Travel Journal & Memories',
    description: 'Log trips with dates, places, and highlights. Add photos or links so you can revisit later.',
    tag: 'Travel',
    whats_inside: ['Trip log', 'Highlights', 'Favorites', 'Photo links'],
    is_free: true,
  },
  {
    title: 'Weekend Getaway Planner',
    description: 'Quick planning for short getaways: one page for destination, stay, and a simple schedule.',
    tag: 'Travel',
    whats_inside: ['Destination ideas', 'Accommodation', '2–3 day outline', 'Packing short list'],
    is_free: true,
  },
  {
    title: 'Flight & Accommodation Tracker',
    description: 'Store confirmation numbers, dates, and links for flights and stays. One place for all trip bookings.',
    tag: 'Travel',
    whats_inside: ['Bookings database', 'Confirmation numbers', 'Dates', 'Links'],
    is_free: true,
  },
  {
    title: 'Local Favorites & Recommendations',
    description: 'Save restaurants, spots, and tips by city. Build your own travel guide for revisits or sharing.',
    tag: 'Travel',
    whats_inside: ['City database', 'Places', 'Categories', 'Notes & ratings'],
    is_free: true,
  },
  {
    title: 'Road Trip Planner',
    description: 'Plan routes, stops, and overnight stays. Add sights and driving times so the road trip is smooth.',
    tag: 'Travel',
    whats_inside: ['Route overview', 'Stops', 'Lodging', 'Driving times'],
    is_free: true,
  },
  {
    title: 'Digital Nomad Base',
    description: 'Track visas, co-working spots, and stays for long-term travel. Stay legal and organized.',
    tag: 'Travel',
    whats_inside: ['Visa tracker', 'Destinations', 'Co-working list', 'Budget overview'],
    is_free: false,
    price_cents: 1999,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Family Vacation Planner',
    description: 'Plan family trips with activities for different ages. Keep everyone’s preferences and must-dos in one place.',
    tag: 'Travel',
    whats_inside: ['Trip overview', 'Activity list', 'Family preferences', 'Packing by person'],
    is_free: true,
  },
  {
    title: 'Solo Travel Checklist',
    description: 'Pre-trip checklist for solo travelers: safety, documents, and practical tips.',
    tag: 'Travel',
    whats_inside: ['Pre-trip checklist', 'Documents', 'Safety notes', 'Emergency contacts'],
    is_free: true,
  },
  {
    title: 'Travel Budget & Spending',
    description: 'Set a trip budget and log spending by category. See how much you spent on food, stays, and activities.',
    tag: 'Travel',
    whats_inside: ['Budget by category', 'Expense log', 'Currency', 'Summary'],
    is_free: true,
  },
  {
    title: 'Places to Revisit',
    description: 'List places you’ve been and want to go back to. Notes on what to do next time.',
    tag: 'Travel',
    whats_inside: ['Place database', 'When visited', 'Revisit notes', 'Priority'],
    is_free: true,
  },
  {
    title: 'Adventure & Activity Tracker',
    description: 'Track hikes, dives, or activities you’ve done. Log difficulty, location, and highlights.',
    tag: 'Travel',
    whats_inside: ['Activity log', 'Location', 'Difficulty', 'Highlights'],
    is_free: true,
  },
  {
    title: 'Travel Hacks & Tips',
    description: 'Your personal list of travel hacks, apps, and tips. Add as you learn so you don’t forget.',
    tag: 'Travel',
    whats_inside: ['Tips database', 'Category', 'Source', 'Tried it?'],
    is_free: true,
  },
  {
    title: 'Seasonal Trip Ideas',
    description: 'Ideas by season: where to go in spring, summer, fall, winter. Plan ahead for weather and events.',
    tag: 'Travel',
    whats_inside: ['Season views', 'Destinations', 'Why this season', 'Links'],
    is_free: true,
  },
  {
    title: 'Passport & Visa Tracker',
    description: 'Expiry dates for passport and visas. Reminders so you renew in time.',
    tag: 'Travel',
    whats_inside: ['Passport expiry', 'Visa list', 'Renewal reminders', 'Notes'],
    is_free: true,
  },
  {
    title: 'Layover & Airport Guide',
    description: 'Notes on airports you’ve used: lounges, food, and transit tips for next time.',
    tag: 'Travel',
    whats_inside: ['Airport database', 'Terminal tips', 'Lounges', 'Transit'],
    is_free: true,
  },
  {
    title: 'Group Trip Coordination',
    description: 'Coordinate a group trip: who’s in, preferences, and shared itinerary so everyone stays aligned.',
    tag: 'Travel',
    whats_inside: ['Participant list', 'Preferences', 'Shared itinerary', 'Packing shared'],
    is_free: true,
  },

  // —— Business ——
  {
    title: 'Startup Operating System',
    description: 'Run strategy, ops, and metrics from one place. For founders and small teams who want clarity without complexity.',
    tag: 'Business',
    whats_inside: ['Strategy one-pager', 'OKRs or goals', 'Metrics dashboard', 'Meeting rhythms'],
    is_free: false,
    price_cents: 2999,
    allow_one_time_purchase: true,
    is_subscription_included: true,
    featured: false,
    popularity_score: 85,
  },
  {
    title: 'Wedding Planning Hub',
    description: 'Plan your big day in one place. Timeline, vendor contacts, budget tracker, and a wedding prep checklist so nothing is missed. For couples who want a stress-free journey to the altar.',
    tag: 'Wedding',
    tags: ['Wedding', 'Productivity', 'Personal'],
    whats_inside: ['Master checklist', 'Vendor list & contacts', 'Budget tracker', 'Timeline & milestones', 'Guest list', 'Inspiration board'],
    is_free: true,
    featured: true,
    popularity_score: 80,
  },
  {
    title: 'UX Research Repository Lite',
    description: "Capture insights. Spot patterns. Take action, without the chaos. This Notion template gives you a beautifully simple way to collect, organise, and prioritise your UX research findings. Whether you're running usability tests, stakeholder interviews, or analysing product analytics, this system helps you make your insights visible, and actionable.",
    tag: 'Creator',
    tags: ['Creator', 'Business'],
    whats_inside: ['Research log', 'Insight clustering board', 'Priority scoring', 'Action backlog'],
    is_free: true,
    popularity_score: 86,
  },
  {
    title: 'Executive Dashboard & Brief',
    description: 'One-page brief: key metrics, priorities, and blockers. Update weekly for leadership alignment.',
    tag: 'Business',
    whats_inside: ['Metrics snapshot', 'Top priorities', 'Blockers', 'Decisions needed'],
    is_free: false,
    price_cents: 2499,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Team Wiki & Knowledge Base',
    description: 'Central place for how your team works: processes, FAQs, and links so onboarding and daily work are easy.',
    tag: 'Business',
    whats_inside: ['Process docs', 'FAQ', 'Tool links', 'Owner index'],
    is_free: true,
  },
  {
    title: 'Meeting Notes & Action Tracker',
    description: 'Consistent format for meeting notes and action items. Never lose a follow-up again.',
    tag: 'Business',
    whats_inside: ['Note template', 'Attendees', 'Actions with owner', 'Due dates'],
    is_free: true,
  },
  {
    title: 'OKR & Quarterly Planning',
    description: 'Set company and team OKRs. Track progress and run quarterly reviews in one workspace.',
    tag: 'Business',
    whats_inside: ['OKR database', 'Company & team', 'Progress', 'Review template'],
    is_free: false,
    price_cents: 1999,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'P&L and Budget Tracker',
    description: 'High-level P&L and budget by category. Track actuals vs plan for small teams.',
    tag: 'Business',
    whats_inside: ['Revenue & costs', 'By category', 'Actual vs budget', 'Notes'],
    is_free: false,
    price_cents: 3499,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Hiring & Recruitment Pipeline',
    description: 'Track candidates by role and stage. Move people through interview and offer in one database.',
    tag: 'Business',
    whats_inside: ['Candidates database', 'Stages', 'Interview notes', 'Offer tracker'],
    is_free: true,
  },
  {
    title: 'Product Roadmap & Backlog',
    description: 'Prioritized roadmap and backlog. Link to specs and track status so product and eng stay aligned.',
    tag: 'Business',
    whats_inside: ['Roadmap view', 'Backlog', 'Status', 'Spec links'],
    is_free: false,
    price_cents: 2799,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Customer Feedback Log',
    description: 'Log feedback from support, sales, and interviews. Tag and prioritize so product can act on it.',
    tag: 'Business',
    whats_inside: ['Feedback database', 'Source', 'Theme tags', 'Priority'],
    is_free: true,
  },
  {
    title: 'Board Meeting Pack',
    description: 'Template for board updates: metrics, highlights, and ask. Keep board prep consistent and fast.',
    tag: 'Business',
    whats_inside: ['Metrics summary', 'Highlights', 'Risks', 'Asks'],
    is_free: false,
    price_cents: 1999,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'SOP & Process Library',
    description: 'Document standard operating procedures. Step-by-step so anyone can run key processes.',
    tag: 'Business',
    whats_inside: ['Process list', 'Step-by-step', 'Owner', 'Last updated'],
    is_free: true,
  },
  {
    title: 'Competitive Intelligence',
    description: 'Track competitors: features, pricing, and positioning. Update as the market changes.',
    tag: 'Business',
    whats_inside: ['Competitor database', 'Features', 'Pricing', 'Notes'],
    is_free: true,
  },
  {
    title: 'Launch Checklist',
    description: 'Pre-launch checklist for product or campaign. Marketing, ops, and support in one list.',
    tag: 'Business',
    whats_inside: ['Checklist by area', 'Owner', 'Due date', 'Done'],
    is_free: true,
  },
  {
    title: '1:1 Meeting Template',
    description: 'Agenda for manager–report 1:1s: wins, challenges, and feedback. Keep 1:1s focused and fair.',
    tag: 'Business',
    whats_inside: ['Agenda template', 'Talking points', 'Action items', 'Follow-up'],
    is_free: true,
  },
  {
    title: 'Incident & Post-Mortem',
    description: 'Log incidents and run post-mortems. What happened, root cause, and actions so it doesn’t repeat.',
    tag: 'Business',
    whats_inside: ['Incident log', 'Post-mortem template', 'Actions', 'Owner'],
    is_free: true,
  },
  {
    title: 'Vendor & Contract Tracker',
    description: 'List vendors and contracts: renewal dates, cost, and owner so nothing auto-renews by surprise.',
    tag: 'Business',
    whats_inside: ['Vendor database', 'Contract dates', 'Cost', 'Owner'],
    is_free: true,
  },
  {
    title: 'Goals & Performance Review',
    description: 'Set goals and run performance reviews. One place for expectations and feedback.',
    tag: 'Business',
    whats_inside: ['Goals', 'Review template', 'Feedback', 'Development plan'],
    is_free: false,
    price_cents: 2299,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Company All-Hands Notes',
    description: 'Template for all-hands: wins, metrics, and Q&A. Keep the whole company aligned.',
    tag: 'Business',
    whats_inside: ['Agenda', 'Wins', 'Metrics', 'Q&A log'],
    is_free: true,
  },
  {
    title: 'Strategic Initiatives Tracker',
    description: 'Track big initiatives: owner, status, and dependencies. So strategy turns into execution.',
    tag: 'Business',
    whats_inside: ['Initiatives database', 'Owner', 'Status', 'Dependencies'],
    is_free: false,
    price_cents: 1999,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },

  // —— Project Management ——
  {
    title: 'Project Roadmap & Timeline',
    description: 'Visual roadmap and timeline for projects. See milestones and dependencies at a glance.',
    tag: 'Project Management',
    whats_inside: ['Project database', 'Timeline view', 'Milestones', 'Dependencies'],
    is_free: false,
    price_cents: 2499,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Kanban Board & Task Flow',
    description: 'Classic kanban: Backlog, In progress, Review, Done. Move tasks as work flows.',
    tag: 'Project Management',
    whats_inside: ['Board view', 'Status columns', 'Assignee', 'Due date'],
    is_free: true,
  },
  {
    title: 'Sprint Planning & Retro',
    description: 'Plan sprints with scope and capacity. Run retros and capture improvements.',
    tag: 'Project Management',
    whats_inside: ['Sprint template', 'Scope', 'Retro template', 'Action items'],
    is_free: true,
  },
  {
    title: 'Ticketing & Support Queue',
    description: 'Manage support or internal tickets. Triage, assign, and resolve in one database.',
    tag: 'Project Management',
    whats_inside: ['Ticket database', 'Priority', 'Assignee', 'Status workflow'],
    is_free: true,
  },
  {
    title: 'Project Calendar & Deadlines',
    description: 'All project milestones and deadlines on one calendar. Never miss a delivery date.',
    tag: 'Project Management',
    whats_inside: ['Calendar view', 'Milestones', 'Deadlines', 'Project filter'],
    is_free: true,
  },
  {
    title: 'Resource & Capacity Planning',
    description: 'See who’s on what and when. Simple capacity view for small teams.',
    tag: 'Project Management',
    whats_inside: ['Project list', 'Assignments', 'Capacity', 'Timeline'],
    is_free: false,
    price_cents: 2799,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'RACI & Responsibility Matrix',
    description: 'Define RACI for initiatives or processes. Clear who’s responsible, accountable, consulted, informed.',
    tag: 'Project Management',
    whats_inside: ['Matrix view', 'Initiatives', 'Roles', 'People'],
    is_free: true,
  },
  {
    title: 'Risk & Blocker Log',
    description: 'Log risks and blockers with owner and mitigation. Escalate and resolve in one place.',
    tag: 'Project Management',
    whats_inside: ['Risk database', 'Owner', 'Mitigation', 'Status'],
    is_free: true,
  },
  {
    title: 'Release & Launch Tracker',
    description: 'Track releases and launches: checklist, owners, and go/no-go so launches are smooth.',
    tag: 'Project Management',
    whats_inside: ['Release checklist', 'Owners', 'Go/no-go', 'Post-launch'],
    is_free: true,
  },
  {
    title: 'Stakeholder Map & Communication',
    description: 'Map stakeholders and plan communication. Who needs to know what and when.',
    tag: 'Project Management',
    whats_inside: ['Stakeholder list', 'Interest', 'Communication plan', 'Updates log'],
    is_free: true,
  },
  {
    title: 'Scope & Change Log',
    description: 'Document scope and change requests. Keep scope creep visible and agreed.',
    tag: 'Project Management',
    whats_inside: ['Scope doc', 'Change log', 'Approval', 'Impact'],
    is_free: true,
  },
  {
    title: 'Project Retrospective Library',
    description: 'Templates for retros: what went well, what didn’t, and action items. Build a habit of learning.',
    tag: 'Project Management',
    whats_inside: ['Retro template', 'Themes', 'Actions', 'Archive'],
    is_free: true,
  },
  {
    title: 'Multi-Project Dashboard',
    description: 'Overview of all projects: status, health, and key dates. For PMs and leads.',
    tag: 'Project Management',
    whats_inside: ['Project list', 'Status', 'Health', 'Key dates'],
    is_free: false,
    price_cents: 1999,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Dependency Map',
    description: 'Map dependencies between projects or tasks. See blockers and critical path.',
    tag: 'Project Management',
    whats_inside: ['Dependency list', 'From/to', 'Type', 'Owner'],
    is_free: true,
  },
  {
    title: 'Project Brief & Charter',
    description: 'One-page project brief: goal, scope, success, and team. Align everyone at kickoff.',
    tag: 'Project Management',
    whats_inside: ['Goal', 'Scope', 'Success criteria', 'Team & roles'],
    is_free: true,
  },
  {
    title: 'Status Report Template',
    description: 'Weekly or monthly status: done, in progress, and blockers. Consistent updates for stakeholders.',
    tag: 'Project Management',
    whats_inside: ['Done', 'In progress', 'Blockers', 'Next period'],
    is_free: true,
  },
  {
    title: 'Design & Dev Handoff',
    description: 'Track handoff from design to dev: specs, assets, and acceptance so nothing is lost.',
    tag: 'Project Management',
    whats_inside: ['Spec links', 'Assets', 'Acceptance', 'Status'],
    is_free: true,
  },
  {
    title: 'Project Templates Library',
    description: 'Reusable templates for project types: marketing, product, ops. Start new projects fast.',
    tag: 'Project Management',
    whats_inside: ['Templates by type', 'Checklist', 'Stakeholders', 'Timeline'],
    is_free: false,
    price_cents: 1799,
    allow_one_time_purchase: true,
    is_subscription_included: true,
    featured: true,
    popularity_score: 86,
  },

  // —— CRM ——
  {
    title: 'Simple CRM & Pipeline',
    description: 'Track leads and deals through stages. Lightweight pipeline for small sales teams.',
    tag: 'CRM',
    whats_inside: ['Deals database', 'Stages', 'Value', 'Contact link'],
    is_free: false,
    price_cents: 2999,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Contact & Company Database',
    description: 'Contacts and companies in one place. Log interactions and next steps.',
    tag: 'CRM',
    whats_inside: ['Contacts', 'Companies', 'Interactions', 'Next steps'],
    is_free: true,
  },
  {
    title: 'Sales Pipeline by Stage',
    description: 'Deals by stage with value and close date. Forecast and prioritize from one view.',
    tag: 'CRM',
    whats_inside: ['Pipeline view', 'Stage', 'Value', 'Close date'],
    is_free: false,
    price_cents: 2499,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Lead Tracker & Source',
    description: 'Where leads come from and how they move. Simple attribution and follow-up.',
    tag: 'CRM',
    whats_inside: ['Lead database', 'Source', 'Status', 'Owner'],
    is_free: true,
  },
  {
    title: 'Proposal & Quote Tracker',
    description: 'Track proposals and quotes sent. Status and value so you know what’s pending.',
    tag: 'CRM',
    whats_inside: ['Proposal list', 'Client', 'Value', 'Status'],
    is_free: true,
  },
  {
    title: 'Account Plan & Strategy',
    description: 'One page per key account: goals, stakeholders, and action plan.',
    tag: 'CRM',
    whats_inside: ['Account overview', 'Stakeholders', 'Goals', 'Actions'],
    is_free: false,
    price_cents: 1999,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Follow-Up & Reminder Queue',
    description: 'Never forget a follow-up. Queue by date and owner so outreach stays on track.',
    tag: 'CRM',
    whats_inside: ['Follow-up list', 'Date', 'Contact', 'Note'],
    is_free: true,
  },
  {
    title: 'Sales Activity Log',
    description: 'Log calls, emails, and meetings. Full activity history per contact or deal.',
    tag: 'CRM',
    whats_inside: ['Activity database', 'Type', 'Contact', 'Outcome'],
    is_free: true,
  },
  {
    title: 'Win/Loss Analysis',
    description: 'Why you won or lost deals. Learn and improve from every outcome.',
    tag: 'CRM',
    whats_inside: ['Deal database', 'Outcome', 'Reasons', 'Learnings'],
    is_free: true,
  },
  {
    title: 'Referral & Partner Tracker',
    description: 'Track referrals and partners. Who sent what and what’s in the pipeline.',
    tag: 'CRM',
    whats_inside: ['Referral list', 'Source', 'Status', 'Reward'],
    is_free: true,
  },
  {
    title: 'Territory & Account Assignment',
    description: 'Assign accounts to reps or territories. Clear ownership and coverage.',
    tag: 'CRM',
    whats_inside: ['Territory list', 'Accounts', 'Owner', 'Target'],
    is_free: false,
    price_cents: 2299,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Contract & Renewal Tracker',
    description: 'Contract end dates and renewal status. Don’t let renewals slip.',
    tag: 'CRM',
    whats_inside: ['Contract database', 'End date', 'Value', 'Renewal status'],
    is_free: true,
  },
  {
    title: 'Competitive Battle Cards',
    description: 'Quick comparison vs competitors. Positioning and talk tracks for sales.',
    tag: 'CRM',
    whats_inside: ['Competitor cards', 'Vs us', 'Talk tracks', 'Objections'],
    is_free: true,
  },
  {
    title: 'Demo & Presentation Log',
    description: 'Track demos given: who, when, and outcome. Follow up with the right message.',
    tag: 'CRM',
    whats_inside: ['Demo log', 'Contact', 'Date', 'Next step'],
    is_free: true,
  },
  {
    title: 'Sales Goals & Quota',
    description: 'Set quota and track progress. Individual and team views.',
    tag: 'CRM',
    whats_inside: ['Quota', 'Actual', 'Pipeline', 'Forecast'],
    is_free: false,
    price_cents: 1999,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Customer Health Score',
    description: 'Simple health score for customers. Usage, support, and engagement in one view.',
    tag: 'CRM',
    whats_inside: ['Customer list', 'Health score', 'Factors', 'Actions'],
    is_free: false,
    price_cents: 2799,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Outreach Sequence Tracker',
    description: 'Track multi-touch sequences: steps, opens, and replies so you know what works.',
    tag: 'CRM',
    whats_inside: ['Sequence template', 'Steps', 'Metrics', 'Contacts'],
    is_free: true,
  },
  {
    title: 'RFP & Response Tracker',
    description: 'Track RFPs: deadline, owner, and status. Win more with organized responses.',
    tag: 'CRM',
    whats_inside: ['RFP database', 'Deadline', 'Owner', 'Sections'],
    is_free: true,
  },
  {
    title: 'Sales Playbook & Scripts',
    description: 'Playbook and scripts by scenario. Consistent messaging across the team.',
    tag: 'CRM',
    whats_inside: ['Scenario list', 'Script', 'Objections', 'Resources'],
    is_free: true,
  },
  {
    title: 'Commission & Incentive Tracker',
    description: 'Track deals and commission. Simple view for reps and managers.',
    tag: 'CRM',
    whats_inside: ['Deal list', 'Rep', 'Commission', 'Paid'],
    is_free: false,
    price_cents: 2499,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },

  // —— Creator & Content Calendar ——
  {
    title: 'Content Calendar & Editorial',
    description: 'Plan content across channels. Ideas, calendar, and status in one place.',
    tag: 'Content Calendar',
    whats_inside: ['Calendar view', 'Channel', 'Status', 'Owner'],
    is_free: true,
  },
  {
    title: 'YouTube & Video Production',
    description: 'Ideas, script, and production status for video content. From idea to publish.',
    tag: 'Creator',
    whats_inside: ['Video database', 'Script', 'Production status', 'Publish date'],
    is_free: true,
  },
  {
    title: 'Newsletter & Email Content',
    description: 'Plan and draft newsletter issues. Topics, drafts, and send dates.',
    tag: 'Creator',
    whats_inside: ['Issue list', 'Topic', 'Draft', 'Send date'],
    is_free: true,
  },
  {
    title: 'Blog & Article Pipeline',
    description: 'Article ideas, outline, and publish status. SEO and content in one pipeline.',
    tag: 'Content Calendar',
    whats_inside: ['Article database', 'Outline', 'Status', 'Publish'],
    is_free: true,
  },
  {
    title: 'Social Media Planner',
    description: 'Plan posts by platform and date. Caption, asset, and hashtags in one row.',
    tag: 'Content Calendar',
    whats_inside: ['Post database', 'Platform', 'Date', 'Caption'],
    is_free: true,
  },
  {
    title: 'Sponsorship & Brand Deals',
    description: 'Track brand deals: brand, offer, and status. Never miss a follow-up.',
    tag: 'Creator',
    whats_inside: ['Deal database', 'Brand', 'Offer', 'Status'],
    is_free: false,
    price_cents: 1999,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Content Repurposing Tracker',
    description: 'Turn one piece into many. Track what’s been repurposed and where it’s published.',
    tag: 'Creator',
    whats_inside: ['Original', 'Repurposed', 'Channels', 'Links'],
    is_free: true,
  },
  {
    title: 'Idea Bank & Content Seeds',
    description: 'Capture content ideas as they come. Tag and prioritize so you never run out of ideas.',
    tag: 'Content Calendar',
    whats_inside: ['Idea database', 'Tags', 'Priority', 'Status'],
    is_free: true,
  },
  {
    title: 'Launch & Campaign Calendar',
    description: 'Plan launches and campaigns: timeline, assets, and channels in one view.',
    tag: 'Content Calendar',
    whats_inside: ['Campaign list', 'Timeline', 'Assets', 'Channels'],
    is_free: false,
    price_cents: 1799,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Podcast Episode Planner',
    description: 'Plan episodes: topic, guest, and production status. From pitch to publish.',
    tag: 'Creator',
    whats_inside: ['Episode list', 'Topic', 'Guest', 'Status'],
    is_free: true,
  },
  {
    title: 'Creator Income & Expenses',
    description: 'Track creator income by source and expenses. Simple P&L for your creative business.',
    tag: 'Creator',
    whats_inside: ['Income log', 'Expense log', 'By month', 'Summary'],
    is_free: true,
  },
  {
    title: 'Collaboration & Guest Tracker',
    description: 'Track collabs and guest appearances: who, when, and status.',
    tag: 'Creator',
    whats_inside: ['Collab database', 'Partner', 'Format', 'Status'],
    is_free: true,
  },
  {
    title: 'Content Performance Log',
    description: 'Log performance for key content: views, engagement, and learnings.',
    tag: 'Content Calendar',
    whats_inside: ['Content list', 'Metrics', 'Learnings', 'Next time'],
    is_free: true,
  },
  {
    title: 'Editorial Workflow & Approval',
    description: 'Draft → review → approve. Simple workflow for teams that publish content.',
    tag: 'Content Calendar',
    whats_inside: ['Draft', 'Review', 'Approval', 'Publish'],
    is_free: false,
    price_cents: 2299,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Hashtag & Caption Library',
    description: 'Save hashtag sets and caption templates. Reuse and iterate on what works.',
    tag: 'Creator',
    whats_inside: ['Hashtag sets', 'Caption templates', 'By niche', 'Performance'],
    is_free: true,
  },
  {
    title: 'Multi-Platform Content Grid',
    description: 'One content piece, many platforms. Track what goes where and when.',
    tag: 'Content Calendar',
    whats_inside: ['Content database', 'Platforms', 'Adaptation', 'Schedule'],
    is_free: true,
  },
  {
    title: 'Audience & Community Notes',
    description: 'Notes on your audience: questions, feedback, and themes. So content stays relevant.',
    tag: 'Creator',
    whats_inside: ['Feedback log', 'Themes', 'Ideas', 'Priority'],
    is_free: true,
  },
  {
    title: 'Content Batching Checklist',
    description: 'Checklist for batching: record, edit, caption, schedule. Batch like a pro.',
    tag: 'Creator',
    whats_inside: ['Batch checklist', 'By type', 'Tools', 'Schedule'],
    is_free: true,
  },

  // —— Habit Tracker, Health, Fitness ——
  {
    title: 'Atomic Habits Tracker',
    description: 'Track habits with cues, routines, and rewards. Build systems that stick.',
    tag: 'Habit Tracker',
    whats_inside: ['Habit list', 'Cue/routine/reward', 'Daily log', 'Streaks'],
    is_free: true,
  },
  {
    title: 'Daily Rituals & Morning Routine',
    description: 'Morning and evening rituals in one place. Check off and build consistency.',
    tag: 'Habit Tracker',
    whats_inside: ['Ritual checklist', 'AM/PM', 'Streak', 'Notes'],
    is_free: true,
  },
  {
    title: 'Habit Stacking & Triggers',
    description: 'Stack new habits on existing ones. Define triggers and track execution.',
    tag: 'Habit Tracker',
    whats_inside: ['Habit stack', 'Trigger', 'New habit', 'Log'],
    is_free: true,
  },
  {
    title: '30-Day Challenge Tracker',
    description: 'Run 30-day challenges: goal, daily check-in, and reflection at the end.',
    tag: 'Habit Tracker',
    whats_inside: ['Challenge template', 'Daily log', 'Reflection', 'Next challenge'],
    is_free: true,
  },
  {
    title: 'Sleep & Recovery Log',
    description: 'Log sleep and recovery: hours, quality, and factors. Spot what helps.',
    tag: 'Health',
    whats_inside: ['Sleep log', 'Quality', 'Factors', 'Weekly view'],
    is_free: true,
  },
  {
    title: 'Workout & Training Log',
    description: 'Log workouts: type, duration, and notes. Track progress over time.',
    tag: 'Fitness',
    whats_inside: ['Workout log', 'Type', 'Duration', 'Notes'],
    is_free: true,
  },
  {
    title: 'Meal Planning & Nutrition',
    description: 'Plan meals and track nutrition. Simple and flexible for real life.',
    tag: 'Health',
    whats_inside: ['Meal plan', 'Recipes', 'Grocery', 'Notes'],
    is_free: true,
  },
  {
    title: 'Mental Health & Mood Check-In',
    description: 'Daily or weekly mood and mental health check-ins. Private and for you only.',
    tag: 'Health',
    whats_inside: ['Check-in template', 'Mood', 'Gratitude', 'Reflection'],
    is_free: true,
  },
  {
    title: 'Water & Hydration Tracker',
    description: 'Track water intake and stay hydrated. Simple daily goal and log.',
    tag: 'Fitness',
    whats_inside: ['Daily goal', 'Log', 'Reminders', 'Weekly view'],
    is_free: true,
  },
  {
    title: 'Steps & Activity Tracker',
    description: 'Log steps or activity minutes. Set goals and see trends.',
    tag: 'Fitness',
    whats_inside: ['Daily log', 'Goal', 'Trend', 'Notes'],
    is_free: true,
  },
  {
    title: 'Meditation & Mindfulness',
    description: 'Track meditation and mindfulness practice. Duration and notes.',
    tag: 'Health',
    whats_inside: ['Session log', 'Duration', 'Type', 'Notes'],
    is_free: true,
  },
  {
    title: 'Symptom & Health Log',
    description: 'Log symptoms and health events. Useful for doctor visits and patterns.',
    tag: 'Health',
    whats_inside: ['Symptom log', 'Date', 'Severity', 'Notes'],
    is_free: true,
  },
  {
    title: 'Running or Cycling Log',
    description: 'Log runs or rides: distance, time, and route. Track PRs and progress.',
    tag: 'Fitness',
    whats_inside: ['Activity log', 'Distance', 'Time', 'PRs'],
    is_free: true,
  },
  {
    title: 'Gym & Strength Program',
    description: 'Track strength workouts: exercises, sets, and reps. Progressive overload made simple.',
    tag: 'Fitness',
    whats_inside: ['Program template', 'Exercises', 'Sets/reps', 'Progress'],
    is_free: false,
    price_cents: 1499,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Screen Time & Digital Wellness',
    description: 'Log screen time and digital habits. Awareness before change.',
    tag: 'Health',
    whats_inside: ['Daily log', 'By device', 'Goals', 'Reflection'],
    is_free: true,
  },
  {
    title: 'Year of Habits Vision',
    description: 'Pick habits for the year and track monthly. One place for intention and progress.',
    tag: 'Habit Tracker',
    whats_inside: ['Habits for year', 'Monthly check', 'Reflection', 'Adjustments'],
    is_free: true,
  },
  {
    title: 'Habit Streak Dashboard',
    description: 'See all habit streaks in one view. Motivate with consistency.',
    tag: 'Habit Tracker',
    whats_inside: ['Streak view', 'By habit', 'Longest streak', 'Calendar'],
    is_free: true,
  },
  {
    title: 'Rest Day & Recovery Plan',
    description: 'Plan rest and recovery. Stretching, mobility, and light activity.',
    tag: 'Fitness',
    whats_inside: ['Rest day template', 'Activities', 'Notes', 'Schedule'],
    is_free: true,
  },
  {
    title: 'Health Goals & Annual Check-Up',
    description: 'Health goals and annual check-up prep. Track and remember.',
    tag: 'Health',
    whats_inside: ['Goals', 'Check-up prep', 'Results', 'Follow-up'],
    is_free: true,
  },

  // —— Wedding, Event Planning, Lifestyle, Personal ——
  {
    title: 'Wedding Budget & Expenses',
    description: 'Track wedding budget by category. Stay on budget without stress.',
    tag: 'Wedding',
    whats_inside: ['Budget by category', 'Actual spend', 'Vendor payments', 'Remaining'],
    is_free: true,
  },
  {
    title: 'Guest List & Seating',
    description: 'Guest list with RSVP and seating. One source of truth for the big day.',
    tag: 'Wedding',
    whats_inside: ['Guest database', 'RSVP', 'Seating', 'Dietary'],
    is_free: true,
  },
  {
    title: 'Event Run of Show',
    description: 'Run of show for any event: timeline, roles, and checklist so the day runs smoothly.',
    tag: 'Event Planning',
    whats_inside: ['Timeline', 'Roles', 'Checklist', 'Contacts'],
    is_free: true,
  },
  {
    title: 'Party & Gathering Planner',
    description: 'Plan parties and gatherings: menu, tasks, and guest list.',
    tag: 'Event Planning',
    whats_inside: ['Menu', 'Task list', 'Guests', 'Shopping'],
    is_free: true,
  },
  {
    title: 'Conference & Trip Agenda',
    description: 'Agenda for conferences or work trips: sessions, meetings, and notes.',
    tag: 'Event Planning',
    whats_inside: ['Schedule', 'Sessions', 'Contacts', 'Notes'],
    is_free: true,
  },
  {
    title: 'Birthday & Celebration Tracker',
    description: 'Track birthdays and celebrations. Never forget a special day.',
    tag: 'Lifestyle',
    whats_inside: ['Date list', 'Gift ideas', 'Sent', 'Notes'],
    is_free: true,
  },
  {
    title: 'Holiday Planning & Prep',
    description: 'Plan holidays: gifts, meals, and tasks so the season is calm.',
    tag: 'Event Planning',
    whats_inside: ['Gift list', 'Meal plan', 'Task list', 'Calendar'],
    is_free: true,
  },
  {
    title: 'Personal Goals & Life Plan',
    description: 'Set and track personal goals by area of life. Yearly and quarterly.',
    tag: 'Personal',
    whats_inside: ['Goals by area', 'Quarterly', 'Progress', 'Review'],
    is_free: true,
  },
  {
    title: 'Bucket List & Life Goals',
    description: 'Bucket list and life goals in one place. Tick off as you go.',
    tag: 'Personal',
    whats_inside: ['Bucket list', 'Categories', 'Done', 'Notes'],
    is_free: true,
  },
  {
    title: 'Daily Journal & Reflection',
    description: 'Daily journal with prompts. Reflect and learn from each day.',
    tag: 'Personal',
    whats_inside: ['Daily template', 'Prompts', 'Gratitude', 'Learnings'],
    is_free: true,
  },
  {
    title: 'Home & Household Management',
    description: 'Household tasks, maintenance, and contacts. One place for home admin.',
    tag: 'Lifestyle',
    whats_inside: ['Task list', 'Maintenance', 'Contacts', 'Schedule'],
    is_free: true,
  },
  {
    title: 'Pet Care & Vet Tracker',
    description: 'Track pet care: vet visits, meds, and notes. Never miss a dose or appointment.',
    tag: 'Lifestyle',
    whats_inside: ['Vet log', 'Meds', 'Appointments', 'Notes'],
    is_free: true,
  },
  {
    title: 'Gift Ideas & Giving List',
    description: 'Save gift ideas by person or occasion. Be ready for any celebration.',
    tag: 'Lifestyle',
    whats_inside: ['Person list', 'Ideas', 'Budget', 'Given'],
    is_free: true,
  },
  {
    title: 'Moving & Relocation Checklist',
    description: 'Checklist for moving: change of address, utilities, and tasks so nothing is missed.',
    tag: 'Event Planning',
    whats_inside: ['Checklist', 'Address change', 'Utilities', 'Timeline'],
    is_free: true,
  },
  {
    title: 'Date Night & Ideas Bank',
    description: 'Ideas for dates and quality time. Never run out of plans.',
    tag: 'Lifestyle',
    whats_inside: ['Idea list', 'Category', 'Tried', 'Rating'],
    is_free: true,
  },
  {
    title: 'Self-Care & Me Time',
    description: 'Plan and track self-care. Rest and recharge on purpose.',
    tag: 'Personal',
    whats_inside: ['Activity list', 'Schedule', 'Log', 'Reflection'],
    is_free: true,
  },
  {
    title: 'New Year Resolutions & Review',
    description: 'Set resolutions and review monthly. Make the new year count.',
    tag: 'Personal',
    whats_inside: ['Resolutions', 'Monthly check', 'Wins', 'Adjustments'],
    is_free: true,
  },

  // —— Freelance, Knowledge ——
  {
    title: 'Freelance Client & Project Tracker',
    description: 'Track clients and projects: scope, status, and invoices. For solo freelancers.',
    tag: 'Freelance',
    whats_inside: ['Client database', 'Projects', 'Status', 'Invoice log'],
    is_free: true,
  },
  {
    title: 'Freelance Proposal & Contract',
    description: 'Templates for proposals and contracts. Send professional docs every time.',
    tag: 'Freelance',
    whats_inside: ['Proposal template', 'Contract template', 'Sends', 'Status'],
    is_free: true,
  },
  {
    title: 'Freelance Time & Billing',
    description: 'Log time and billable hours. Simple for hourly or project-based work.',
    tag: 'Freelance',
    whats_inside: ['Time log', 'Project', 'Billable', 'Invoice link'],
    is_free: false,
    price_cents: 1799,
    allow_one_time_purchase: true,
    is_subscription_included: true,
  },
  {
    title: 'Personal Knowledge Base',
    description: 'Your second brain: notes, links, and topics. Find anything fast.',
    tag: 'Knowledge',
    whats_inside: ['Topic structure', 'Notes', 'Links', 'Tags'],
    is_free: true,
  },
  {
    title: 'Learning & Course Tracker',
    description: 'Track courses and learning: progress, notes, and next steps.',
    tag: 'Knowledge',
    whats_inside: ['Course list', 'Progress', 'Notes', 'Resources'],
    is_free: true,
  },
  {
    title: 'Book Notes & Highlights',
    description: 'Notes and highlights from books. Build a searchable library of ideas.',
    tag: 'Knowledge',
    whats_inside: ['Book database', 'Highlights', 'Notes', 'Tags'],
    is_free: true,
  },
  {
    title: 'Tarot Learning Vault',
    description: 'A beautifully organized tarot learning database for beginners and intermediate readers. Browse all 78 cards with upright & reversed meanings, keywords, and symbolism. Includes a spread encyclopedia with step-by-step layouts, a daily draw journal to track your interpretations over time, and a practice reading log so you can see your progress. Designed to help you actually learn tarot — not just collect card definitions.',
    tag: 'Knowledge',
    whats_inside: [
      '78 card meanings with upright & reversed interpretations',
      'Spread encyclopedia (Celtic Cross, 3-card, Past-Present-Future, and more)',
      'Daily draw journal with reflection prompts',
      'Practice reading log with accuracy tracking',
      'Keyword & symbolism quick-reference',
      'Suit & element cheat sheets',
    ],
    is_free: false,
    price_cents: 900,
    allow_one_time_purchase: true,
    is_subscription_included: true,
    featured: true,
    popularity_score: 89,
  },
  {
    title: 'AI Engineering Skill Path',
    description: 'A step-by-step learning path to build AI systems from scratch. Covers foundations, ML core, deep learning, and production skills with curated resources and hands-on projects.',
    tag: 'Knowledge',
    whats_inside: [
      'Phased roadmap: Foundations → ML Core → Deep Learning → LLM Apps → MLOps',
      'Resource tracker per phase (courses, papers, repos)',
      'Weekly sprint planner and progress tracking',
      'Mini-project briefs and milestone retrospectives',
      'Interview prep question bank',
    ],
    is_free: false,
    price_cents: 1900,
    allow_one_time_purchase: true,
    is_subscription_included: true,
    featured: false,
  },
  {
    title: 'AI Engineering Roadmap by Data With Baraa',
    description: 'A complete step-by-step learning path to build real AI systems from scratch — the same way they are built in top companies. Covers foundations, ML core, deep learning, LLM applications, MLOps, and capstone projects. By Data With Baraa.',
    tag: 'Knowledge',
    whats_inside: [
      '6-phase roadmap: Foundations → ML Core → Deep Learning → LLM Apps → MLOps → Capstone',
      'Curated resource tracker (courses, papers, repos) per phase',
      'Weekly skill sprint planner with time blocks',
      'Hands-on mini-project briefs for each phase',
      'Milestone retrospective templates',
      'Interview prep question bank',
    ],
    is_free: false,
    price_cents: 1900,
    allow_one_time_purchase: true,
    is_subscription_included: true,
    featured: true,
    popularity_score: 101,
  },
  {
    title: 'Research & Source Library',
    description: 'Save research and sources. Tag and cite with ease.',
    tag: 'Knowledge',
    whats_inside: ['Source database', 'Tags', 'Summary', 'Citation'],
    is_free: true,
  },
  {
    title: 'Skill & Competency Matrix',
    description: 'Track skills and competency levels. Plan learning and growth.',
    tag: 'Knowledge',
    whats_inside: ['Skill list', 'Level', 'Evidence', 'Goals'],
    is_free: true,
  },
  {
    title: 'Freelance Pipeline & Inquiries',
    description: 'Track incoming inquiries and proposals. Respond and close more work.',
    tag: 'Freelance',
    whats_inside: ['Inquiry list', 'Source', 'Status', 'Response'],
    is_free: true,
  },
  {
    title: 'Freelance Tax & Expense Log',
    description: 'Log business expenses for freelancers. Simpler tax time.',
    tag: 'Freelance',
    whats_inside: ['Expense log', 'Category', 'Receipt', 'Quarter'],
    is_free: true,
  },
  {
    title: 'Wiki & Team Knowledge',
    description: 'Team wiki: how we work, decisions, and FAQs. Onboard and align faster.',
    tag: 'Knowledge',
    whats_inside: ['Process docs', 'Decisions', 'FAQ', 'Owner'],
    is_free: true,
  },
  {
    title: 'Glossary & Definitions',
    description: 'Glossary of terms and definitions. One source of truth for the team.',
    tag: 'Knowledge',
    whats_inside: ['Term database', 'Definition', 'Context', 'Links'],
    is_free: true,
  },

  // —— Notion Marketplace Replicas (free open-source templates) ——
  {
    title: 'Travel Bucket Wish List',
    description: 'A simple and visual way to track every place you dream of visiting. Add destinations to a gallery database with cover photos, mark them as wishlisted, planned, or visited, and filter by continent or season. Each entry holds travel notes, budget estimates, and a packing checklist so you are ready when the trip becomes real.',
    tag: 'Travel',
    whats_inside: [
      'Destination gallery with cover images',
      'Status tags: Wish List / Planned / Visited',
      'Filter by continent and best season',
      'Budget and packing notes per entry',
      'Priority ranking for your top picks',
      'Quick-add button for new destinations',
    ],
    is_free: true,
  },
  {
    title: 'The 2026 Social Media Content Planner',
    description: 'Plan, create, and schedule content across every social platform in one workspace. Organize posts by platform (Instagram, TikTok, YouTube, LinkedIn, X), track their status from idea to published, and view everything on a calendar or kanban board. Includes a hashtag bank, caption drafts area, and weekly analytics snapshot so you always know what is working.',
    tag: 'Content Calendar',
    whats_inside: [
      'Multi-platform content database',
      'Calendar and board views by status',
      'Caption drafts and hashtag bank',
      'Post status pipeline: Idea > Draft > Scheduled > Published',
      'Weekly analytics snapshot section',
      'Repurpose tracker for cross-platform content',
    ],
    is_free: true,
  },
  {
    title: 'Content Planner for TikTok & Instagram Influencers',
    description: 'A week-by-week content planner built specifically for TikTok and Instagram creators. Map out your posts, reels, stories, and TikToks in one view. Track content ideas from concept to posting, organize by content pillar, and keep your hashtag sets and audio trends handy. Designed to help creators stay consistent and grow their audience without feeling overwhelmed.',
    tag: 'Creator',
    whats_inside: [
      'Weekly content calendar for TikTok and Instagram',
      'Content pillars and idea bank',
      'Reel, Story, and TikTok trackers',
      'Hashtag sets and trending audio log',
      'Post performance notes per entry',
      'Batch content workflow: Film > Edit > Caption > Schedule',
    ],
    is_free: true,
    featured: true,
    popularity_score: 88,
  },
];

// Build static templates: each definition becomes one Template with unique slug and varied rating/popularity.
export const STATIC_TEMPLATES: Template[] = TEMPLATE_DEFINITIONS.map((def, index) =>
  buildTemplate(def, index),
);
